name: Automatic Agentic Radar

on:
  pull_request:

jobs:
  run-agentic-radar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history is available

      - name: Get list of committed files in the PR
        id: changed_files
        run: |
          mkdir -p analysis_folder
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > changed_files.txt
          while IFS= read -r file; do
            cp --parents "$file" analysis_folder/ 2>/dev/null || true
          done < changed_files.txt

      - name: Extract framework from commit message
        id: detect_framework
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          FRAMEWORK="unknown"
          for word in "crewai" "langgraph" "n8n" "openai-agents"; do
            if echo "$COMMIT_MSG" | grep -iq "$word"; then
              FRAMEWORK="$word"
              break
            fi
          done
          echo "Detected framework: $FRAMEWORK"
          echo "FRAMEWORK=$FRAMEWORK" >> $GITHUB_ENV

      - name: Set up Python 3.10
        if: ${{ env.FRAMEWORK != 'unknown' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install Agentic Radar
        if: ${{ env.FRAMEWORK != 'unknown' }}
        run: |
          python -m pip install --upgrade pip
          pip install agentic-radar[crewai,openai-agents]
      
      - name: Run Agentic Radar
        id: agentic_radar
        if: ${{ env.FRAMEWORK != 'unknown' }}
        run: |
          agentic-radar scan $FRAMEWORK -i analysis_folder -o report.html
        continue-on-error: true
        
      - name: Upload report.html
        id: upload_artifact
        if: ${{ env.FRAMEWORK != 'unknown' && steps.agentic_radar.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: agentic-radar-report
          path: report.html

      - name: Comment on PR with download link
        if: ${{ env.FRAMEWORK != 'unknown' && steps.agentic_radar.outcome == 'success' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The Agentic Radar report has been generated. You can download the report using the link below:
            - [Download Agentic Radar Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload_artifact.outputs.artifact-id }})
