name: Automatic Agentic Radar

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get list of committed files
        id: changed_files
        run: |
          mkdir -p analysis_folder
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          while IFS= read -r file; do
            cp --parents "$file" analysis_folder/ 2>/dev/null || true
          done < changed_files.txt

      - name: Extract framework from commit message
        id: detect_framework
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          FRAMEWORK="unknown"
          for word in "crewai" "langgraph" "n8n" "openai-agents"; do
            if echo "$COMMIT_MSG" | grep -iq "$word"; then
              FRAMEWORK="$word"
              break
            fi
          done
          echo "Detected framework: $FRAMEWORK"
          echo "FRAMEWORK=$FRAMEWORK" >> $GITHUB_ENV

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Agentic Radar
        run: |
          python -m pip install --upgrade pip
          pip install agentic-radar[crewai]
      
      - name: Run Agentic Radar
        run: |
          agentic-radar -i analysis_folder -o report.html $FRAMEWORK

      - name: Upload report.html
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
